apiVersion: kubermatic.k8s.io/v1
kind: Preset
metadata:
    name: kkp
    namespace: kubermatic
spec:
    aws:
        accessKeyID: ENC[AES256_GCM,data:DZCR9W2psqP4kOjGABWBEgvVstM=,iv:1J8xlyvKcvd3mkerOw+c6+MVTx/Z7IV5j355tcOxQeE=,tag:epGckuo/PpjZWI51U1Qc+g==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:/MCU0z/7bbPMWsTgf5ok1/f01us3Fei9K69OTeE9hZT7h7ogTtO0FQ==,iv:6bN0QAfevTEMQhXrj4cR10SHjmBL6jOvu0gzMJ8NSrg=,tag:tx1vEvltFGxnc77UX+jCdQ==,type:str]
        vpcId: vpc-9ab315f0
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnxn5s3wz0wwlv0rv2g2l9rlmg9zg8hd938mxruzck70llxq5a0q6ude3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TWJxNk5nNHpIcHVVaVBv
            WjVnQ3FQVTFNTTY1K1F4YmpxRTljcTBVbm5FCloxL2xiUGZRcjdvSjhlVmE3dklM
            RWJvZVMwZXNMR1NlcFByZW5kR1lWZjgKLS0tIGFWb2xVWjFXeVlCaDZXcjcvYnpE
            c0tqeFZYeFRuRVN4WjZVcFQrQUdKWG8K6bGNxrEEm4thMgXmLH7YDVeTbutTHsvZ
            Q7PiQRnGvq2/U00l/PxHfn3O4GcqJDot/cNhQXppWHjxrCNmqM3u2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-20T12:07:24Z"
    mac: ENC[AES256_GCM,data:ULOckAv12o6ny9hwusFoFHz1RgjkRCUMfW2W6evch02zm5hPDkcCqUMkem+LhLYpuCloBeRlvAmxgMm4PnHBfEuZ0ImWbfKMGoEl3iea+NpBo5t+oKIzz5DE2fDfgV1tqq7HzXGms7h2eBVC9Ca2LF0kzWMdqvM4knCkj/ow5kg=,iv:puzEFz4Kw7DxdYASm1dRU0UjYxoX6QvuZXl88l1Lrmc=,tag:RQ9W7lIK2MpVX84R04WXfA==,type:str]
    pgp: []
    encrypted_regex: (accessKeyID|secretAccessKey|username|password)
    version: 3.7.1
