apiVersion: operator.kubermatic.io/v1alpha1
kind: KubermaticConfiguration
metadata:
    name: kubermatic
    namespace: kubermatic
spec:
    ingress:
        domain: kkp-demo-cds.lab.kubermatic.io
        certificateIssuer:
            apiGroup: null
            kind: ClusterIssuer
            name: letsencrypt-prod
        className: nginx
    auth:
        clientID: kubermatic
        issuerClientID: kubermaticIssuer
        skipTokenIssuerTLSVerify: true
        tokenIssuer: https://kkp-demo-cds.lab.kubermatic.io/dex
        issuerClientSecret: ENC[AES256_GCM,data:W5OEMccuuvuHUjKwmBVFYWvuFkTcdJZzIFITQvIhesEMwOKHhI4zOWq3xw==,iv:vENbFqF007beHEUQi/FVsOnKdHrKR+Tj/xNYiEjXtJE=,tag:4Isp5Sm6Pcrtv9Ol+5RMwg==,type:str]
        issuerCookieKey: ENC[AES256_GCM,data:Vnmd/dPQqhxSAvUIRYfKrus1PF96GD6hGqYd32kzouw=,iv:3fw+RbwjVXpLA0FQNfCNWab1yLf24K48xDFefK+wzOk=,tag:Ossth9bwkfyzh5ULyzAI2w==,type:str]
        serviceAccountKey: ENC[AES256_GCM,data:aFU43IQkynIGmiXAvKiMBFo/j5xT/19A9Pty+LjmUbw=,iv:THRQBczZ8awCRvvws/8+ma6pFZnvl0qYSBJsJ9SzGrw=,tag:IeHylT/v8addTCzwHRN++A==,type:str]
        issuerRedirectURL: https://kkp-demo-cds.lab.kubermatic.io/api/v1/kubeconfig
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fnxn5s3wz0wwlv0rv2g2l9rlmg9zg8hd938mxruzck70llxq5a0q6ude3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQW9TUUlzY2toUlhXQi91
            c0tUNW1Obm9yZjI0dTJyU2JMc2pYY3ZNS3k0CmptT1FhSFdTdlE0dmMvRFpSOGRk
            RSswaXNEamxjZ0YwcWtyNXhSazdjVlUKLS0tIG5uZmFkcnZCbHJWb0x4NWtrWXZI
            YTI5elc3dmNOcXFqdHA3ejFVaWFuclEKdbO+n5peEBnVsuvCEcM+eoVMfeO1L47t
            S0/MOTCsWz5XjUE26Mgk2vUCpvXbp/S3nEHiZ6EZrhaV/dQC5oqBkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-20T12:07:24Z"
    mac: ENC[AES256_GCM,data:v3IbSHykxGSD+Jgl4E8sxn5RRasgrPPw0r/3oIthA64/UJS4tZxm1Rw2PfKECf1h+xVO0nWJVfbeeZyZ3rNKM9gmuZOCZoLNIotSrlyWctB5V+ZAH2MywZFZQF9E6K2GCfMyjYD5D7gwH/AEl1J7nosQ2Vi4gQ9f05Gnj4qjx6s=,iv:t4yTtiMaAsgpPoUFqqlypLyjvStmvHapofZHV1Vaao4=,tag:2qb8LYrlzLPjLV2kiRcnrg==,type:str]
    pgp: []
    encrypted_regex: (issuerClientSecret|issuerCookieKey|serviceAccountKey)
    version: 3.7.1
