kubermaticOperator:
    image:
        tag: v2.18.0
dex:
    ingress:
        host: kkp-demo-cds.lab.kubermatic.io
    certIssuer:
        name: letsencrypt-prod
        kind: ClusterIssuer
    env:
        - name: KUBERNETES_POD_NAMESPACE
          value: oauth
    staticPasswords:
        - email: michal@kubermatic.com
          hash: ENC[AES256_GCM,data:9eFv/Si6k5azX8BhlUXMTpDUuAF9c1AexHOMm07HUuwyMt3cPtNLcs8hi+KUqNtmOql+nYobt9AvU+Q4,iv:XqvocuZ2gsVRui9jcHiHx2Q+bQSfdGSAjxq4t1e2J+c=,tag:14iCH9yLYSvo791EColr6g==,type:str]
          username: michal@kubermatic.com
          userID: d538fece-a352-4b7b-8075-3033efb342a3
    clients:
        - id: kubermatic
          name: Kubermatic
          secret: ENC[AES256_GCM,data:QTH0kjhHrA9W8mfXXiOR+mnBZPWPAcI8//z6gkG5WvoeRv8oNdHMJKbYMg==,iv:cldxb4Z8TmybN9+3mGqDJ8En/UTw57dxOKtxFc6RLX8=,tag:9bEspo/zQNYZKO2GbmVdcw==,type:str]
          RedirectURIs:
            - https://kkp-demo-cds.lab.kubermatic.io
            - https://kkp-demo-cds.lab.kubermatic.io/projects
        - id: kubermaticIssuer
          name: Kubermatic OIDC Issuer
          secret: ENC[AES256_GCM,data:8uSAOzZ3L/Ng0bUfnjEI0w==,iv:J/UIFvCAL2dH6fNvpfnyU7ufeqUfRHsOqSzjnbF0Bbc=,tag:Xom5Ah14VXN5+4Txu/5iiQ==,type:str]
          RedirectURIs:
            - https://kkp-demo-cds.lab.kubermatic.io/api/v1/kubeconfig
        - id: prometheus
          name: Prometheus
          secret: ENC[AES256_GCM,data:6yqCuNBpWCdmG/fG6L+DLg==,iv:xEXkYZuh1YH05Cz6NDzKY/dKb6E1W7qayAnDR+V0jn4=,tag:mPTj9N0A4y0OGE5LMOcjvg==,type:str]
          RedirectURIs:
            - https://prometheus.kkp-demo-cds.lab.kubermatic.io/oauth/callback
        - id: alertmanager
          name: Alertmanager
          secret: ENC[AES256_GCM,data:x3/1XX+kw7cU+Xyi39I/Hw==,iv:hHIpCyu5gThg1qY9MjrmyomlkjegTvuuvRiy7vsd1Ng=,tag:Y9MbbBRlxJ4T5iQqjpf80g==,type:str]
          RedirectURIs:
            - https://alertmanager.kkp-demo-cds.lab.kubermatic.io/oauth/callback
        - id: grafana
          name: Grafana
          secret: ENC[AES256_GCM,data:MBcdjAr48NiWQwXN8P9iKg==,iv:Dw/tkpMByCF8CRftCC+cCuejvCSa+GkKGnPGKN1XnNQ=,tag:ZLJpaGq15besoULM6MF52w==,type:str]
          RedirectURIs:
            - https://grafana.kkp-demo-cds.lab.kubermatic.io/oauth/callback
        - id: karma
          name: Karma
          secret: ENC[AES256_GCM,data:myZvuUOs8dstAl8xyoMeEQ==,iv:Z3oDCtiyUQOnpwiTsqhL8TCztHlQeIIMiEu1f0au7/8=,tag:Tgj1UPws2RXCk2ikIwFWZw==,type:str]
          RedirectURIs:
            - https://karma.kkp-demo-cds.lab.kubermatic.io/oauth/callback
alertmanager:
    host: alertmanager.kkp-demo-cds.lab.kubermatic.io
grafana:
    user: admin
    password: ENC[AES256_GCM,data:pABxWgKIBDsjCawQJW4ZEQ==,iv:FODDHLWjZTp75Hlc5Mxn6zFzLdcj5d0Lv+Mhp5BvhEQ=,tag:ULC95IfkefL1UBQ8H+tKQQ==,type:str]
    provisioning:
        configuration:
            auto_assign_org_role: Editor
            disable_login_form: false
        datasources:
            lokiServices:
                - loki
prometheus:
    host: prometheus.kkp-demo-cds.lab.kubermatic.io
    storageSize: 50Gi
    tsdb:
        retentionTime: 7d
    ruleFiles:
        - /etc/prometheus/rules/general-*.yaml
        - /etc/prometheus/rules/kubermatic-*.yaml
        - /etc/prometheus/rules/managed-*.yaml
iap:
    oidc_issuer_url: https://kkp-demo-cds.lab.kubermatic.io/dex
    deployments:
        prometheus:
            name: prometheus
            ingress:
                host: prometheus.kkp-demo-cds.lab.kubermatic.io
            upstream_service: prometheus.monitoring.svc.cluster.local
            upstream_port: 9090
            client_id: prometheus
            client_secret: ENC[AES256_GCM,data:6DdduTRXo+ApxDmdf0DuRA==,iv:WJqLO/VeJpoiUE6XW8nBX7bWuD8Fy/8jc1BgDqYz5Jk=,tag:XnBnoBBsqaIvqQWvXjea3w==,type:str]
            encryption_key: ENC[AES256_GCM,data:PHtn4wK4u27+zV/5I02O+hr7ZtdyxEPAy+jltkEHemE=,iv:tZnPT7+KyAwT7kcFeSy99csl6yYSugGizBIX+0MO2PY=,tag:GAPPLujhVWc0cx/wKx+2xw==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        alertmanager:
            name: alertmanager
            ingress:
                host: alertmanager.kkp-demo-cds.lab.kubermatic.io
            upstream_service: alertmanager.monitoring.svc.cluster.local
            upstream_port: 9093
            client_id: alertmanager
            client_secret: ENC[AES256_GCM,data:3TfUuphE2ArdYTmAMpKpHA==,iv:YL6O9/qJPVu13n5dLZ7ZduHUuTpKfP0e5hVuENFeRDM=,tag:B/Q8tP/8iI8ryP24sGpmDQ==,type:str]
            encryption_key: ENC[AES256_GCM,data:b9N+L0pwlEqMJ/yVuwnYACSLKC4TkZdoVRSP2Xtw5fU=,iv:ss+IdG8GM74mcnZ33uqhYDhM2nYFHSmmpIpSZWKGVH4=,tag:oeUg5F5PyVd9LYdsIyMdOw==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        grafana:
            name: grafana
            ingress:
                host: grafana.kkp-demo-cds.lab.kubermatic.io
            upstream_service: grafana.monitoring.svc.cluster.local
            upstream_port: 3000
            client_id: grafana
            client_secret: ENC[AES256_GCM,data:jeHHVgusXEbxjMj5zitk5A==,iv:0yISI7nhLlfqLUPeGEyJZFmWpGabKFKJCWYBHQxV7ng=,tag:7nuUV1CkNufZXW3M7YKcxg==,type:str]
            encryption_key: ENC[AES256_GCM,data:6Z29WpNY65oSZ1ZovNLSBtAe8SM9PirDmddXTigrZ3Y=,iv:PXDDknOU1L71haLk0bW05F5Q5AK6kKv6zNm+ZEfrCPg=,tag:/ULngT8YuuI4EHQMZvon9Q==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /api/health
        karma:
            name: karma
            ingress:
                host: karma.kkp-demo-cds.lab.kubermatic.io
            upstream_service: karma.monitoring.svc.cluster.local
            upstream_port: 8080
            client_id: karma
            client_secret: ENC[AES256_GCM,data:6RdUcWpZX7hYHbEEr0gycQ==,iv:qn1mAEBrdEuGVffE0VCok1FATa2PD8QBZVHpXXD3crw=,tag:b1e51T4o6yLTatL8uNlfjA==,type:str]
            encryption_key: ENC[AES256_GCM,data:cWhjv2v5JWnAYJbZYw8UDTi7djGTnnPn9w7Nn87kMaY=,iv:k5+n9BI/Cb4IGt0arg7oNJv2UgpxVJKKAz5n57YMXjI=,tag:Pvrnax2jnlS5wG14/GLxWw==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
certManager:
    clusterIssuers:
        letsencrypt-prod:
            email: michal@kubermatic.com
        letsencrypt-staging:
            email: michal@kubermatic.com
minio:
    storeSize: 50Gi
    storageClass: kubermatic-backup
    credentials:
        accessKey: ENC[AES256_GCM,data:RGCZIES/6PzL89ZAMVVD4NAb7nG+FIxqgaPo/THCc7U=,iv:oMhw5UZu2yegvciG5lJAt9fl32h+Cc4MoyImPuMR6AA=,tag:KQEWMncoznljCtqchlVPcQ==,type:str]
        secretKey: ENC[AES256_GCM,data:r1K6XBSg3cB0iEOTFGBTGKdfwN9pYxIATHDmo/tNik0=,iv:ZEc1qx6aLr6HnBivOc6zSTyCSZSUlaN6XWzexjgedEc=,tag:3Zczm1NHLhnx9SCnK33tig==,type:str]
telemetry:
    # uuid is the unique identifier of the client where the agent is running.
    # This field is required and will print an error message when that entry is missing.
    uuid: 6110a471-8acf-4cec-9d21-6b6c3707b037
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f4rjk4pgr06eceu53crpw0svlsjpms6vaqkkkelctvg47zn9caeqhjh9gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRjZhMFB4djRkUEdVQnlZ
            TTBieG9KZVB1bCttRXg0bGV6TkI2RmgvYkd3Cmgxd2x5TnBHRXdINm5HREphVUJm
            Y2NhUU1xMjF2bGNtRSszNXJVc0NFMFEKLS0tIHp4OFdad3NpTHdVUEtNcTlXRGdD
            RWVobkhZQjVOR2tENVBhL1lnWHJYK1UKzJXX4nMf9LbSMyXmte+RMcw4jE8plFPq
            GUYqbe7g73/7hXertRWJ2g3W3cRy2jVLE9Yf/sG4Z4Cd7U5lR76Yxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-20T15:31:37Z"
    mac: ENC[AES256_GCM,data:GuTSlgr0z87r4BVzA82o2KIgTrQYhiHsTTTms/qoeot7d/8PoERgLMJSncrcrUc//4QXFJboPIyiXVL0wIblhR2UHNOZZTzsJ07OAoZ+/ZH6XzzdbNEurGlfsQhxgObd7KpryJkGdFBMUkzi/1499/hAZT3C684frEL0fWFJ+4M=,iv:qz6HkbtsXoF5VSjbCKHReu8lNaFY8Wa/CqICdibPofc=,tag:0Z8ATceRA5gfe4z8wDhozg==,type:str]
    pgp: []
    encrypted_regex: (hash|secret|password|encryption_key|accessKey)
    version: 3.7.1
